In [9]:
from pathlib import Path
import sys

root = Path.cwd().resolve()
if not (root / "src").exists():
    root = root.parent

if str(root) not in sys.path:
    sys.path.append(str(root))

In [10]:
from src.load_data import *
from src.cleaning import *

df = load_decision_data()
df = clean_decisions(df)

In [11]:
from src.get_match import get_match_incidents, get_incidents_by_team

df = get_match_incidents("Argentina Vs Cape Verde")
df

,incident_id,match,stage,minute,favored_team,underdog_team,team_benefited,team_hurt,incident_type,decision,favored_team_benefited,score,call_correctness,confidence,video_timestamp,VAR_involved,standard_fit,notes
13,ARG-CPV-R32-01,argentina vs cape verde,R32,16,argentina,cape verde,argentina,cape verde,Foul,Free Kick,True,2.0,0.2,0.6,1:34,False,0.80,Cape Verdean defender makes tackle on Messi. C...
14,ARG-CPV-R32-02,argentina vs cape verde,R32,67,argentina,cape verde,argentina,cape verde,Foul,Yellow Card,True,1.0,0.4,0.6,8:21,False,0.90,Cape Verdean defender is booked for a shirt tu...
15,ARG-CPV-R32-03,argentina vs cape verde,R32,72,argentina,cape verde,argentina,cape verde,Game Management,Whistle Blown Before Keeper Appears Ready,True,1.0,0.7,0.5,9:10,False,-0.75,"Strangely, the referee blows the whistle for a..."
16,ARG-CPV-R32-04,argentina vs cape verde,R32,97,argentina,cape verde,argentina,cape verde,Foul,No Free Kick,True,1.5,0.1,0.8,13:21,False,-1.00,Cape Verdean attacker is clearly fouled by Arg...

In [12]:
from src.scores import calculate_weighted_score, match_bias_score

print(match_bias_score("Argentina Vs Cape Verde"))

3.26

In [13]:
df = load_decision_data()
df = clean_decisions(df)
for i in df["match"].drop_duplicates():
    print(f"Match: {i}, Score: {match_bias_score(i)}")

Match: south africa vs canada, Score: -1.02
Match: brazil vs japan, Score: -0.16
Match: germany vs paraguay, Score: -2.3
Match: mexico vs ecuador, Score: 0.1
Match: usa vs bosnia and herzegovina, Score: 0.22
Match: portugal vs croatia, Score: 0.3
Match: switzerland vs algeria, Score: 0.88
Match: australia vs egypt, Score: 0.33
Match: argentina vs cape verde, Score: 3.26
Match: norway vs ivory coast, Score: 0.3
Match: england vs dr congo, Score: -0.94
Match: spain vs austria, Score: -0.25
Match: belgium vs senegal, Score: 1.48
Match: colombia vs ghana, Score: -0.18
Match: canada vs morocco, Score: 0.89
Match: france vs paraguay, Score: -2.13
Match: brazil vs norway, Score: 1.22
Match: usa vs belgium, Score: 0.0
Match: switzerland vs colombia, Score: -0.98
Match: mexico vs england, Score: -0.7
Match: argentina vs egypt, Score: 2.94
Match: argentina vs switzerland, Score: 0.34
Match: norway vs england, Score: -0.65
Match: france vs morocco, Score: 0.36
Match: argentina vs england, Score: 0.44
Match: france vs spain, Score: 0.87
Match: france vs england, Score: -0.08
Match: spain vs argentina, Score: 0.3

In [14]:
from src.aggregate import *
print(calculate_weighted_score(df[df["team_benefited"] == "brazil"]))
print(team_impact("egypt"))

33    0.330000
34    0.890955
dtype: float64
-2.61

In [17]:
from src.create_csv import *
create_match_sheet()
ms = load_match_sheet()
ms = ms.groupby("stage")["match_name"].count()
ms.head(100)

stage
3P      1
F       1
QF      3
R16     7
R32    14
SF      2
Name: match_name, dtype: int64

In [18]:
teams = load_team_sheet()
teams = teams[teams["impact"] >= 0]
teams.head()

          team  matches_played  incident_count  impact  impact_per_match
1       brazil               2               3    2.16              1.08
3       mexico               2               4    2.06              1.03
5     portugal               1               1    1.04              1.04
6  switzerland               3               3    1.91              0.64
8    argentina               5              11   12.09              2.42

In [19]:
create_processed_incidents()
incidents = load_incidents()
match_sheet = load_match_sheet()
team_sheet = load_team_sheet()
incidents[["incident_id", "abs_bias_significance", "decision", "unfairness_bucket"]].sort_values("abs_bias_significance", ascending=False)

,incident_id,abs_bias_significance,decision,unfairness_bucket
3,GER-PAR-R32-02,2.127630,Goal Disallowed,robbery
42,ARG-EGY-R16-02,1.951984,Goal Disallowed,robbery
16,ARG-CPV-R32-04,1.536867,No Free Kick,Unfair
13,ARG-CPV-R32-01,1.202110,Free Kick,Unfair
0,RSA-CAN-R32-01,1.024909,No Penalty,Unfair
37,SUI-COL-R16-01,0.975992,No Penalty,Minorly unfair
18,ENG-COD-R32-01,0.941135,No Penalty,Minorly unfair
34,BRA-NOR-R16-02,0.890955,Penalty,Minorly unfair
10,SUI-ALG-R32-01,0.878393,No Free Kick,Minorly unfair
51,FRA-ESP-SF-01,0.871647,Penalty,Minorly unfair
20,BEL-SEN-R32-01,0.859135,No Free Kick,Minorly unfair
31,PAR-FRA-R16-06,0.853815,Yellow Card,Minorly unfair
28,PAR-FRA-R16-03,0.830028,No Free Kick,Minorly unfair
29,PAR-FRA-R16-04,0.806855,No Free Kick,Minorly unfair
30,PAR-FRA-R16-05,0.632515,No Yellow Card,Minorly unfair
43,ARG-EGY-R16-03,0.621188,No Penalty,Minorly unfair
21,BEL-SEN-R32-02,0.621117,Penalty,Minorly unfair
46,NOR-ENG-QF-02,0.553451,No Free Kick,Minorly unfair
38,MEX-ENG-R16-01,0.552104,Red Card,Minorly unfair
54,ESP-ARG-F-02,0.543478,Goal Disallowed,Minorly unfair
8,USA-BIH-R32-04,0.530330,Yellow Card,Minorly unfair
25,CAN-MAR-R16-03,0.520529,Yellow Card,Minorly unfair
50,ENG-ARG-SF-01,0.439196,No Yellow Card,Questionable
47,NOR-ENG-QF-03,0.416543,No Penalty,Questionable
6,USA-BIH-R32-02,0.414078,Red Card,Questionable
7,USA-BIH-R32-03,0.406663,No Free Kick,Questionable
14,ARG-CPV-R32-02,0.404339,Yellow Card,Questionable
26,PAR-FRA-R16-01,0.376454,Yellow Card,Questionable
41,ARG-EGY-R16-01,0.368480,Penalty,Questionable
27,PAR-FRA-R16-02,0.367696,No Yellow Card,Questionable
44,ARG-SUI-QF-01,0.338093,Second Yellow Card,Questionable
33,BRA-NOR-R16-01,0.330000,Penalty,Questionable
45,NOR-ENG-QF-01,0.317745,Goal Disallowed,Questionable
9,POR-CRO-R32-01,0.301869,Penalty,Questionable
5,USA-BIH-R32-01,0.301869,No Penalty,Questionable
17,CIV-NOR-R32-01,0.296985,No Yellow Card,Questionable
11,AUS-EGY-R32-01,0.254558,No Yellow Card,Questionable
19,ESP-AUT-R32-02,0.252005,Goal Disallowed,Questionable
53,ESP-ARG-F-01,0.241495,Second Yellow Card,Probably fair
48,FRA-MAR-QF-01,0.236129,Penalty,Probably fair
40,MEX-ENG-R16-03,0.216004,Penalty,Probably fair
23,CAN-MAR-R16-01,0.204494,No Free Kick,Probably fair
22,COL-GHA-R32-01,0.177097,No Penalty,Probably fair
2,GER-PAR-R32-01,0.167705,No Penalty,Probably fair
24,CAN-MAR-R16-02,0.162635,Free Kick,Probably fair
1,BRA-JPN-R32-01,0.157744,No Free Kick,Probably fair
36,USA-BEL-R16-02,0.129414,No Free Kick,Probably fair
35,USA-BEL-R16-01,0.128798,Free Kick,Probably fair
49,FRA-MAR-QF-02,0.123431,No Free Kick,Probably fair
32,PAR-FRA-R16-07,0.119534,Penalty,Probably fair
15,ARG-CPV-R32-03,0.112968,Whistle Blown Before Keeper Appears Ready,Probably fair
4,MEX-ECU-R32-01,0.096598,Free Kick,Probably fair
52,FRA-ENG-3P-01,0.079689,Penalty,Probably fair
12,AUS-EGY-R32-02,0.078262,Free Kick,Probably fair
39,MEX-ENG-R16-02,0.069728,Penalty,Probably fair